"""Constants for the corona_in_zahlen integration."""
DOMAIN = "corona_in_zahlen"
BASE_DOMAIN = "https://www.corona-in-zahlen.de/landkreise/"
ATTRIBUTION = "Data provided by RKI"
OPTION_TOTAL = "total"
